### ISSUE TITLE
new issue detecterd precaution

### ISSUE THREAD

**Issue by VictorGonzalez2704** [kasimxo/IABigData-24-25#1]
new issue be careful

**Comment by kasimxo** [comment]
Issue has been succesfully fixed, now the project is careful, be safe.

**Comment by kasimxo** [comment]
Issue has been succesfully fixed, now the project is careful, be safe.

**Comment by VictorGonzalez2704** [comment]
thanks yu kasimxo yu ar de best 👍😎🥵😉😗😊
